# Generated by Django 4.1.3 on 2022-12-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_age_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('amateur', 'Amateur'), ('home_cook', 'Home Cook'), ('expert', 'Expert')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
