# Generated by Django 4.1.3 on 2022-12-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_photo'),
        ('recipes', '0004_alter_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
