# Generated by Django 4.1.3 on 2022-12-17 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
