# Generated by Django 4.1.3 on 2022-12-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('expert', 'Expert')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('beef_recipes', 'Beef recipes'), ('chicken_recipes', 'Chicken recipes'), ('pork_recipes', 'Pork recipes'), ('stir_fry', 'Stir fry'), ('sushi', 'Sushi'), ('soup', 'Soup'), ('dessert', 'Dessert'), ('salad', 'Salad'), ('appetizers', 'Appetizers'), ('pasta', 'Pasta'), ('snacks', 'Snacks'), ('sea_food', 'Sea food'), ('sandwiches', 'Sandwiches'), ('pizza', 'Pizza'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(choices=[('roast', 'Roast'), ('bake', 'Bake'), ('fry', 'Fry'), ('grill', 'Grill'), ('saute', 'Saute'), ('steam', 'Steam'), ('boil', 'Boil'), ('deep_fry', 'Deep fry')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subcategory',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('dairy_free', ' Dairy-free'), ('gluten_free', 'Gluten-free')], max_length=11),
        ),
    ]
