# Generated by Django 4.1.3 on 2022-12-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cooking_method_alter_recipe_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('beef_recipes', 'Beef recipes'), ('chicken_recipes', 'Chicken recipes'), ('pork_recipes', 'Pork recipes'), ('lamb_recipes', 'Lamb recipes'), ('stir_fry', 'Stir fry'), ('sushi', 'Sushi'), ('soup', 'Soup'), ('dessert', 'Dessert'), ('salad', 'Salad'), ('appetizers', 'Appetizers'), ('pasta', 'Pasta'), ('snacks', 'Snacks'), ('sea_food', 'Sea food'), ('sandwiches', 'Sandwiches'), ('pizza', 'Pizza'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subcategory',
            field=models.CharField(choices=[('none', 'None'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('dairy_free', ' Dairy-free'), ('gluten_free', 'Gluten-free')], max_length=11),
        ),
    ]
