# Generated by Django 4.1.3 on 2022-12-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelike',
            old_name='photo',
            new_name='recipe',
        ),
    ]
